# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('introducao', models.TextField(blank=True, null=True)),
                ('indicacoes', models.TextField(blank=True, null=True)),
                ('farmacodinamica', models.TextField(blank=True, null=True)),
                ('farmacocinetica', models.TextField(blank=True, null=True)),
                ('contraindicacoes', models.TextField(blank=True, null=True)),
                ('precaucoes', models.TextField(blank=True, null=True)),
                ('gravidez', models.TextField(blank=True, null=True)),
                ('interacoes', models.TextField(blank=True, null=True)),
                ('posologia', models.TextField(blank=True, null=True)),
                ('reacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
