# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario_farmacos', '0005_farmaco_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmaco',
            name='lactacao',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='farmaco',
            name='pediatria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='contraindicacoes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='farmacocinetica',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='farmacodinamica',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='gravidez',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='indicacoes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='interacoes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='introducao',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='posologia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='precaucoes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='reacoes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
