# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('true_false', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tf_question',
            options={'ordering': ['especialidade'], 'verbose_name': 'True/False Question', 'verbose_name_plural': 'True/False Questions'},
        ),
    ]
