# Generated by Django 2.0.7 on 2018-12-11 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sintoma', '0002_sintoma_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sintoma',
            name='user',
        ),
    ]
