# Generated by Django 2.0.7 on 2018-12-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sintoma', '0003_remove_sintoma_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sintoma',
            name='descricao',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
