# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario_medico', '0002_auto_20171108_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('introducao', models.TextField(blank=True, max_length=50, null=True)),
                ('manifestacoes', models.TextField(blank=True, max_length=50, null=True)),
                ('exames', models.TextField(blank=True, max_length=50, null=True)),
                ('tratamento', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
