# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario_doencas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doenca',
            name='url',
            field=models.SlugField(help_text='a user friendly url', max_length=60, null=True, verbose_name='user friendly url'),
        ),
    ]
