# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario_doencas', '0003_auto_20180620_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doenca',
            name='exames',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='introducao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='manifestacoes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='tratamento',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
