# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario_doencas', '0005_doenca_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='doenca',
            name='diagnostico',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
