# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario_doencas', '0006_doenca_diagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='doenca',
            name='prescricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='diagnostico',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='exames',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='introducao',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='manifestacoes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='tratamento',
            field=models.TextField(blank=True, help_text='objetivos do tratamento', max_length=1000, null=True, verbose_name='objetivos do tratamento'),
        ),
    ]
