# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario_doencas', '0008_auto_20180621_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doenca',
            name='diagnostico',
            field=models.TextField(blank=True, help_text='diagnostico', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='exames',
            field=models.TextField(blank=True, help_text='exames', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='introducao',
            field=models.TextField(blank=True, help_text='introducao', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='manifestacoes',
            field=models.TextField(blank=True, help_text='manifestacoes', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='prescricao',
            field=models.TextField(blank=True, help_text='prescricao', null=True),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='texto',
            field=models.TextField(blank=True, help_text='texto acessorio', null=True),
        ),
    ]
