# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario_alimentos', '0003_auto_20180620_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='beneficios',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='alimento',
            name='componentes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='alimento',
            name='consumo',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='alimento',
            name='nome_cientifico',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alimento',
            name='nomes_populares',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='alimento',
            name='tabela_nutricional',
            field=models.TextField(blank=True),
        ),
    ]
