# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario_alimentos', '0004_auto_20180620_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='beneficios',
            field=models.TextField(blank=True, help_text='beneficios', max_length=500),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='componentes',
            field=models.TextField(blank=True, help_text='componentes', max_length=500),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='consumo',
            field=models.TextField(blank=True, help_text='consumo', max_length=500),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='nome_cientifico',
            field=models.CharField(blank=True, help_text='nome cientifico', max_length=200),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='nomes_populares',
            field=models.CharField(blank=True, help_text='nomes populares', max_length=500),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='tabela_nutricional',
            field=models.TextField(blank=True, help_text='tabela nutricional'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='texto',
            field=models.TextField(blank=True, help_text='texto acessorio', null=True),
        ),
    ]
