# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='descricao',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descricao'),
        ),
    ]
