# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='enunciado',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Enunciado'),
        ),
    ]
