# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0025_artigo_exercicios'),
        ('quiz', '0004_auto_20180204_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artigos.Especialidade', verbose_name='Categoria'),
        ),
    ]
