# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artigos.Especialidade', verbose_name='Especialidade'),
        ),
    ]
