# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0027_auto_20180204_1457'),
        ('quiz', '0006_auto_20180204_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['especialidade'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='question',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artigos.Especialidade', verbose_name='Especialidade'),
        ),
        migrations.AddField(
            model_name='question',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artigos.Tema', verbose_name='Tema'),
        ),
    ]
