# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_question_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(help_text='Enter the question text that you want displayed', max_length=2000, verbose_name='Question'),
        ),
    ]
