# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20180326_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='figure',
            field=models.ImageField(blank=True, null=True, upload_to='img/quiz', verbose_name='Figure'),
        ),
    ]
