# Generated by Django 2.0.7 on 2018-08-05 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180805_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
