# Generated by Django 2.0.7 on 2018-08-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='categoria',
            field=models.ManyToManyField(related_name='categorias', to='chat.Categoria'),
        ),
    ]
