# Generated by Django 2.0.7 on 2018-09-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='estudante',
            name='artigos_favoritos',
        ),
        migrations.RemoveField(
            model_name='estudante',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='estudante',
            name='semestre',
        ),
        migrations.AddField(
            model_name='estudante',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudante',
            name='faculdade',
            field=models.CharField(choices=[('1', 'ESCS'), ('2', 'UNB'), ('3', 'UCB'), ('4', 'UNICEUB'), ('5', 'FACIPLAC')], default='ESCS', max_length=1, verbose_name='Instituição'),
        ),
        migrations.AddField(
            model_name='estudante',
            name='matricula',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='primeiro_nome',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='ultimo_nome',
            field=models.CharField(default='', max_length=30),
        ),
    ]
