# Generated by Django 2.0.7 on 2018-10-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20181002_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilestudante',
            name='user',
        ),
        migrations.DeleteModel(
            name='PerfilEstudante',
        ),
    ]
