# Generated by Django 2.0.7 on 2018-09-30 20:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contas', '0002_auto_20180930_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudante',
            new_name='PerfilEstudante',
        ),
    ]
