# Generated by Django 2.0.7 on 2018-10-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20180930_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilestudante',
            name='faculdade',
            field=models.CharField(choices=[('1', 'ESCS'), ('2', 'UNB'), ('3', 'UCB'), ('4', 'UNICEUB'), ('5', 'FACIPLAC')], default='ESCS', max_length=50, verbose_name='Instituição'),
        ),
    ]
