# Generated by Django 2.0.7 on 2018-10-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_auto_20181001_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilestudante',
            name='faculdade',
            field=models.CharField(choices=[('1', 'ESCS'), ('2', 'UNB'), ('3', 'UCB'), ('4', 'UNICEUB'), ('5', 'FACIPLAC')], default='1', max_length=1, verbose_name='Instituição'),
        ),
    ]
