# Generated by Django 2.0.7 on 2018-10-02 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_auto_20181001_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilestudante',
            name='faculdade',
        ),
    ]
