# Generated by Django 2.0.7 on 2018-10-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilestudante_faculdade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilestudante',
            name='faculdade',
            field=models.CharField(choices=[('1', '----'), ('2', 'ESCS'), ('3', 'UNB'), ('4', 'UCB'), ('5', 'UNICEUB'), ('6', 'FACIPLAC')], default='1', max_length=1, verbose_name='Instituição'),
        ),
    ]
