# Generated by Django 2.0.7 on 2018-10-27 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20181014_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('1', 'Masculino'), ('2', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('primeiro_nome', models.CharField(default='', max_length=30)),
                ('ultimo_nome', models.CharField(default='', max_length=30)),
                ('follows', models.ManyToManyField(related_name='followed_by', to='usuarios.PerfilUsuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfilestudante',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='perfilestudante',
            name='user',
        ),
        migrations.DeleteModel(
            name='PerfilEstudante',
        ),
    ]
