# Generated by Django 2.0.7 on 2018-10-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20181027_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='usuarios.PerfilUsuario'),
        ),
    ]
