# Generated by Django 2.0.7 on 2018-10-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20181027_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilsaude',
            name='meta_peso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
