# Generated by Django 2.0.7 on 2018-10-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20181002_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilestudante',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='usuarios.PerfilEstudante'),
        ),
    ]
