# Generated by Django 2.0.7 on 2018-10-28 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20181027_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilsaude',
            name='data_nascimento',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
