# Generated by Django 2.0.7 on 2018-10-28 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20181027_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilsaude',
            old_name='meta_peso',
            new_name='peso',
        ),
    ]
