# Generated by Django 2.0.7 on 2018-11-28 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0004_auto_20181128_1415'),
        ('recomendacao', '0001_initial'),
        ('medicamento', '0001_initial'),
        ('sintoma', '0001_initial'),
        ('usuarios', '0009_auto_20181027_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeusMedicamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meus_medicamentos', models.ManyToManyField(blank=True, to='medicamento.Medicamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeusSintomas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meus_sintomas', models.ManyToManyField(blank=True, to='sintoma.Sintoma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MinhaDieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minha_dieta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dieta.Dieta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MinhasRecomendacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minhas_recomendacoes', models.ManyToManyField(blank=True, to='recomendacao.Recomendacao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
