# Generated by Django 2.0.7 on 2018-12-11 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sintoma', '0003_remove_sintoma_user'),
        ('usuarios', '0010_meusmedicamentos_meussintomas_minhadieta_minhasrecomendacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meussintomas',
            name='meus_sintomas',
        ),
        migrations.AddField(
            model_name='meussintomas',
            name='meus_sintomas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sintoma.Sintoma'),
        ),
    ]
