# Generated by Django 2.0.7 on 2018-11-02 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('quantidade', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
                ('calorias', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refeicao', models.CharField(choices=[('1', 'Desjejum'), ('2', 'Almoço'), ('3', 'Jantar'), ('4', 'Lanche')], max_length=1)),
                ('data', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('alimento', models.ManyToManyField(to='dieta.Alimento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
