# Generated by Django 2.0.7 on 2018-11-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='calorias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
