# Generated by Django 2.0.7 on 2018-11-03 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dieta', '0002_auto_20181102_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almoco_dom', models.ManyToManyField(related_name='almoco_dom', to='dieta.Alimento')),
                ('almoco_qua', models.ManyToManyField(related_name='almoco_qua', to='dieta.Alimento')),
                ('almoco_qui', models.ManyToManyField(related_name='almoco_qui', to='dieta.Alimento')),
                ('almoco_sab', models.ManyToManyField(related_name='almoco_sab', to='dieta.Alimento')),
                ('almoco_seg', models.ManyToManyField(related_name='almoco_seg', to='dieta.Alimento')),
                ('almoco_sex', models.ManyToManyField(related_name='almoco_sex', to='dieta.Alimento')),
                ('almoco_ter', models.ManyToManyField(related_name='almoco_ter', to='dieta.Alimento')),
                ('desjejum_dom', models.ManyToManyField(related_name='desjejum_dom', to='dieta.Alimento')),
                ('desjejum_qua', models.ManyToManyField(related_name='desjejum_qua', to='dieta.Alimento')),
                ('desjejum_qui', models.ManyToManyField(related_name='desjejum_qui', to='dieta.Alimento')),
                ('desjejum_sab', models.ManyToManyField(related_name='desjejum_sab', to='dieta.Alimento')),
                ('desjejum_seg', models.ManyToManyField(related_name='desjejum_seg', to='dieta.Alimento')),
                ('desjejum_sex', models.ManyToManyField(related_name='desjejum_sex', to='dieta.Alimento')),
                ('desjejum_ter', models.ManyToManyField(related_name='desjejum_ter', to='dieta.Alimento')),
                ('jantar_dom', models.ManyToManyField(related_name='jantar_dom', to='dieta.Alimento')),
                ('jantar_qua', models.ManyToManyField(related_name='jantar_qua', to='dieta.Alimento')),
                ('jantar_qui', models.ManyToManyField(related_name='jantar_qui', to='dieta.Alimento')),
                ('jantar_sab', models.ManyToManyField(related_name='jantar_sab', to='dieta.Alimento')),
                ('jantar_seg', models.ManyToManyField(related_name='jantar_seg', to='dieta.Alimento')),
                ('jantar_sex', models.ManyToManyField(related_name='jantar_sex', to='dieta.Alimento')),
                ('jantar_ter', models.ManyToManyField(related_name='jantar_ter', to='dieta.Alimento')),
                ('lanche1_dom', models.ManyToManyField(related_name='lanche1_dom', to='dieta.Alimento')),
                ('lanche1_qua', models.ManyToManyField(related_name='lanche1_qua', to='dieta.Alimento')),
                ('lanche1_qui', models.ManyToManyField(related_name='lanche1_qui', to='dieta.Alimento')),
                ('lanche1_sab', models.ManyToManyField(related_name='lanche1_sab', to='dieta.Alimento')),
                ('lanche1_seg', models.ManyToManyField(related_name='lanche1_seg', to='dieta.Alimento')),
                ('lanche1_sex', models.ManyToManyField(related_name='lanche1_sex', to='dieta.Alimento')),
                ('lanche1_ter', models.ManyToManyField(related_name='lanche1_ter', to='dieta.Alimento')),
                ('lanche2_dom', models.ManyToManyField(related_name='lanche2_dom', to='dieta.Alimento')),
                ('lanche2_qua', models.ManyToManyField(related_name='lanche2_qua', to='dieta.Alimento')),
                ('lanche2_qui', models.ManyToManyField(related_name='lanche2_qui', to='dieta.Alimento')),
                ('lanche2_sab', models.ManyToManyField(related_name='lanche2_sab', to='dieta.Alimento')),
                ('lanche2_seg', models.ManyToManyField(related_name='lanche2_seg', to='dieta.Alimento')),
                ('lanche2_sex', models.ManyToManyField(related_name='lanche2_sex', to='dieta.Alimento')),
                ('lanche2_ter', models.ManyToManyField(related_name='lanche2_ter', to='dieta.Alimento')),
                ('lanche3_dom', models.ManyToManyField(related_name='lanche3_dom', to='dieta.Alimento')),
                ('lanche3_qua', models.ManyToManyField(related_name='lanche3_qua', to='dieta.Alimento')),
                ('lanche3_qui', models.ManyToManyField(related_name='lanche3_qui', to='dieta.Alimento')),
                ('lanche3_sab', models.ManyToManyField(related_name='lanche3_sab', to='dieta.Alimento')),
                ('lanche3_seg', models.ManyToManyField(related_name='lanche3_seg', to='dieta.Alimento')),
                ('lanche3_sex', models.ManyToManyField(related_name='lanche3_sex', to='dieta.Alimento')),
                ('lanche3_ter', models.ManyToManyField(related_name='lanche3_ter', to='dieta.Alimento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='refeicao',
            name='alimento',
        ),
        migrations.RemoveField(
            model_name='refeicao',
            name='user',
        ),
        migrations.DeleteModel(
            name='Refeicao',
        ),
    ]
