# Generated by Django 2.0.7 on 2018-12-05 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0006_refeicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refeicao',
            name='alimento',
        ),
        migrations.AddField(
            model_name='refeicao',
            name='alimento',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='dieta.Alimento'),
            preserve_default=False,
        ),
    ]
