# Generated by Django 2.0.7 on 2018-12-05 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0007_auto_20181205_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='refeicao',
            name='refeicao',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dieta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
