# Generated by Django 2.0.7 on 2018-12-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0008_auto_20181205_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refeicao',
            options={'verbose_name': 'Refeicao', 'verbose_name_plural': 'Refeicoes'},
        ),
    ]
