# Generated by Django 2.0.7 on 2018-12-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0011_auto_20181211_1947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Almoço',
            new_name='Almoco',
        ),
    ]
