# Generated by Django 2.0.7 on 2018-12-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0014_auto_20181211_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='porcao',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5),
        ),
    ]
