# Generated by Django 2.0.7 on 2018-12-11 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0016_auto_20181211_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lanche1',
            name='alimento',
        ),
        migrations.RemoveField(
            model_name='lanche1',
            name='dieta',
        ),
        migrations.DeleteModel(
            name='Lanche1',
        ),
    ]
