# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_saude', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='assunto',
        ),
        migrations.AddField(
            model_name='assunto',
            name='materia',
            field=models.ManyToManyField(blank=True, to='portal_saude.Materia', verbose_name='Materia'),
        ),
    ]
