# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_saude', '0002_auto_20180527_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assunto',
            name='materia',
        ),
        migrations.AddField(
            model_name='materia',
            name='assunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_saude.Assunto', verbose_name='Assunto'),
        ),
    ]
