# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_saude', '0004_auto_20180527_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patologia', models.CharField(blank=True, max_length=250, null=True, verbose_name='Patologia')),
            ],
            options={
                'verbose_name': 'Patologia',
                'verbose_name_plural': 'Patologias',
            },
        ),
        migrations.AddField(
            model_name='materia',
            name='patologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_saude.Patologia', verbose_name='Patologia'),
        ),
    ]
