# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_saude', '0006_auto_20180527_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='destaque_semana',
        ),
        migrations.AddField(
            model_name='materia',
            name='destaque_patologia',
            field=models.BooleanField(default=False, help_text='Se marcado, o materia sera mostrado na página destaque da patologia. Marcar 3 por patologia', verbose_name='Materia destaque da patologia'),
        ),
    ]
