# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_saude', '0007_auto_20180605_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='figura_menor',
        ),
    ]
