# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_saude', '0008_remove_materia_figura_menor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='destaque_geral1',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='destaque_geral2',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='destaque_geral3',
        ),
    ]
