# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercicio',
            old_name='exercicio_historia',
            new_name='alternativa1',
        ),
        migrations.RenameField(
            model_name='exercicio',
            old_name='exercicio_resposta',
            new_name='alternativa2',
        ),
        migrations.RenameField(
            model_name='exercicio',
            old_name='categoria',
            new_name='ano',
        ),
        migrations.RenameField(
            model_name='exercicio',
            old_name='exercicio_img',
            new_name='exercicio_img1',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='nome',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='alternativa3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='alternativa4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='alternativa5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='data_de_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='enunciado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='especialidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='exercicio_img2',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='instituicao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='prova',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
