# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0002_auto_20180118_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='data_de_criacao',
        ),
    ]
