# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0004_exercicio_data_de_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='tema',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
