# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0006_exercicio_localidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='simulado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
