# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0007_exercicio_simulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='alternativa10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='alternativa6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='alternativa7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='alternativa8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='alternativa9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
