# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0008_auto_20180127_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='simulado_top',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
