# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0009_exercicio_simulado_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='alternativa10',
        ),
    ]
