# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links_uteis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituicao',
            options={'verbose_name': 'Instituicao', 'verbose_name_plural': 'Instituicao'},
        ),
        migrations.AddField(
            model_name='link',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='links_uteis.Instituicao', verbose_name='Instituicao'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='instituicao',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Instituicao'),
        ),
    ]
