# Generated by Django 2.0.7 on 2018-10-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glicemia',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='peso',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pressao',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='temperatura',
            old_name='author',
            new_name='user',
        ),
    ]
