# Generated by Django 2.0.7 on 2018-10-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0002_auto_20181021_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperatura',
            old_name='tempetura',
            new_name='temperatura',
        ),
    ]
