# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario_farmaceutico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmaco',
            name='absorcao',
        ),
        migrations.RemoveField(
            model_name='farmaco',
            name='administracao',
        ),
        migrations.RemoveField(
            model_name='farmaco',
            name='alteracaoexames',
        ),
        migrations.RemoveField(
            model_name='farmaco',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='farmaco',
            name='distribuicao',
        ),
        migrations.RemoveField(
            model_name='farmaco',
            name='eliminacao',
        ),
        migrations.RemoveField(
            model_name='farmaco',
            name='lactacao',
        ),
        migrations.RemoveField(
            model_name='farmaco',
            name='marcas',
        ),
        migrations.RemoveField(
            model_name='farmaco',
            name='metabolismo',
        ),
        migrations.RemoveField(
            model_name='farmaco',
            name='pediatria',
        ),
        migrations.RemoveField(
            model_name='farmaco',
            name='rcomum',
        ),
        migrations.RemoveField(
            model_name='farmaco',
            name='rincomum',
        ),
        migrations.RemoveField(
            model_name='farmaco',
            name='rmuitocomum',
        ),
        migrations.RemoveField(
            model_name='farmaco',
            name='rmuitorara',
        ),
        migrations.RemoveField(
            model_name='farmaco',
            name='rnaodefinida',
        ),
        migrations.RemoveField(
            model_name='farmaco',
            name='rrara',
        ),
        migrations.RemoveField(
            model_name='farmaco',
            name='subclasse',
        ),
        migrations.AddField(
            model_name='farmaco',
            name='interacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmaco',
            name='introducao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmaco',
            name='precaucoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmaco',
            name='reacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
