# Generated by Django 2.0.7 on 2018-11-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0001_initial'),
        ('dieta', '0004_auto_20181128_1415'),
        ('recomendacao', '0001_initial'),
        ('sintoma', '0001_initial'),
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='dieta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dieta.Dieta'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='medicamentos',
            field=models.ManyToManyField(blank=True, to='medicamento.Medicamento'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='recomendacoes',
            field=models.ManyToManyField(blank=True, to='recomendacao.Recomendacao'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='sintomas',
            field=models.ManyToManyField(to='sintoma.Sintoma', verbose_name='Sintoma'),
        ),
    ]
