# Generated by Django 2.0.7 on 2018-12-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_auto_20181128_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='dieta',
        ),
    ]
