# Generated by Django 2.0.7 on 2018-10-15 00:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_de_publicacao', models.DateTimeField(blank=True, null=True)),
                ('artigo_inativo', models.BooleanField(default=False, help_text='Se marcado, o artigo sera mostrado como inativo', verbose_name='Artigo inativo')),
                ('artigo_interno', models.BooleanField(default=False, help_text='Se marcado, o artigo sera mostrado apenas para internos conectados', verbose_name='Artigo para Internos')),
                ('destaque_geral', models.BooleanField(default=False, help_text='Se marcado, o artigo sera mostrado na página destaque geral', verbose_name='Artigo destaque geral')),
                ('destaque_semana', models.BooleanField(default=False, help_text='Se marcado, o artigo sera mostrado na página destaque da semana', verbose_name='Artigo destaque da semana')),
                ('modulo', models.CharField(blank=True, max_length=200, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.SlugField(help_text='a user friendly url', max_length=60, null=True, verbose_name='user friendly url')),
                ('apresentacao', models.CharField(blank=True, max_length=200, null=True)),
                ('intro_top', models.CharField(blank=True, max_length=200, null=True)),
                ('introducao', models.TextField(blank=True, null=True)),
                ('intro_figura1', models.ImageField(blank=True, null=True, upload_to='img')),
                ('intro_figura1_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('intro_figura2', models.ImageField(blank=True, null=True, upload_to='img')),
                ('intro_figura2_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('epidemio_top', models.CharField(blank=True, max_length=200, null=True)),
                ('epidemiologia', models.TextField(blank=True, null=True)),
                ('epidemio_figura', models.ImageField(blank=True, null=True, upload_to='img')),
                ('epidemio_figura_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('class_top', models.CharField(blank=True, max_length=200, null=True)),
                ('classificacao', models.TextField(blank=True, null=True)),
                ('clas_figura', models.ImageField(blank=True, null=True, upload_to='img')),
                ('clas_figura_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('etio_top', models.CharField(blank=True, max_length=200, null=True)),
                ('etiologia_fisiopatologia', models.TextField(blank=True, null=True)),
                ('etio_img1', models.ImageField(blank=True, null=True, upload_to='img')),
                ('etio_img1_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('etio_img2', models.ImageField(blank=True, null=True, upload_to='img')),
                ('etio_img2_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('diag_top', models.CharField(blank=True, max_length=200, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('historia_figura', models.ImageField(blank=True, null=True, upload_to='img')),
                ('historia_figura_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('ef_figura', models.ImageField(blank=True, null=True, upload_to='img')),
                ('ef_figura_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('exames_top_h2', models.CharField(blank=True, max_length=200, null=True)),
                ('exames_complementares', models.TextField(blank=True, null=True)),
                ('exames_img1', models.ImageField(blank=True, null=True, upload_to='img')),
                ('exames_img1_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('exames_img2', models.ImageField(blank=True, null=True, upload_to='img')),
                ('exames_img2_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('exames_img3', models.ImageField(blank=True, null=True, upload_to='img')),
                ('exames_img3_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('criterios_top', models.CharField(blank=True, max_length=200, null=True)),
                ('criterios_diagnosticos', models.TextField(blank=True, null=True)),
                ('dd_top_h2', models.CharField(blank=True, max_length=200, null=True)),
                ('diagnostico_diferencial', models.TextField(blank=True, null=True)),
                ('dd_img', models.ImageField(blank=True, null=True, upload_to='img')),
                ('dd_img_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('diag_figura', models.ImageField(blank=True, null=True, upload_to='img')),
                ('diag_figura_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('top1', models.CharField(blank=True, max_length=200, null=True)),
                ('texto1', models.TextField(blank=True, null=True)),
                ('top1_img1', models.ImageField(blank=True, null=True, upload_to='img')),
                ('top1_img1_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('top1_img2', models.ImageField(blank=True, null=True, upload_to='img')),
                ('top1_img2_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('tratamento_top', models.CharField(blank=True, max_length=200, null=True)),
                ('tratamento_e_manejo', models.TextField(blank=True, null=True)),
                ('trat_figura', models.ImageField(blank=True, null=True, upload_to='img')),
                ('trat_figura_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('profilaxia_top', models.CharField(blank=True, max_length=200, null=True)),
                ('profilaxia', models.TextField(blank=True, null=True)),
                ('prof_figura', models.ImageField(blank=True, null=True, upload_to='img')),
                ('prof_figura_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('prognostico_top', models.CharField(blank=True, max_length=200, null=True)),
                ('prognostico', models.TextField(blank=True, null=True)),
                ('prognostico_img', models.ImageField(blank=True, null=True, upload_to='img')),
                ('prognostico_img_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('complicacoes_top', models.CharField(blank=True, max_length=200, null=True)),
                ('complicacoes', models.TextField(blank=True, null=True)),
                ('algoritmo_top', models.CharField(blank=True, default='ALGORITMO', max_length=200, null=True)),
                ('algoritmo_img1', models.ImageField(blank=True, null=True, upload_to='img')),
                ('algoritmo_img1_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('algoritmo_img2', models.ImageField(blank=True, null=True, upload_to='img')),
                ('algoritmo_img2_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('algoritmo_img3', models.ImageField(blank=True, null=True, upload_to='img')),
                ('algoritmo_img3_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('referencias_top', models.CharField(blank=True, default='REFERÊNCIAS', max_length=200, null=True)),
                ('referencias', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Especialidade')),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
                'verbose_name': 'Especialidade',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tema')),
                ('ordem', models.CharField(max_length=250, null=True, verbose_name='Ordem')),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artigos.Especialidade', verbose_name='Especialidade')),
            ],
            options={
                'verbose_name_plural': 'Temas',
                'verbose_name': 'Tema',
            },
        ),
        migrations.CreateModel(
            name='TemaBasico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_basico', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Tema Básico')),
            ],
            options={
                'verbose_name_plural': 'Temas Básicos',
                'verbose_name': 'Tema Básico',
            },
        ),
    ]
