# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-17 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0019_auto_20171116_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='dd_top_h2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='ef_top_h2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='exames_top_h2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='historia_top_h2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
