# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-25 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0020_auto_20171116_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='subtexto7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='subtexto8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='subtop7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='subtop8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
