# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-11 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0021_auto_20171225_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='referencias_top',
            field=models.CharField(blank=True, default='REFERÊNCIAS', max_length=200, null=True),
        ),
    ]
