# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20180204_1503'),
        ('artigos', '0028_artigo_artigo_interno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='exercicios',
        ),
        migrations.AddField(
            model_name='tema',
            name='exercicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz', verbose_name='Exercícios'),
        ),
    ]
