# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0029_auto_20180215_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='destaque_geral',
            field=models.BooleanField(default=False, help_text='Se marcado, o artigo sera mostrado na página destaque geral', verbose_name='Artigo destaque geral'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='destaque_semana',
            field=models.BooleanField(default=False, help_text='Se marcado, o artigo sera mostrado na página destaque da semana', verbose_name='Artigo destaque da semana'),
        ),
    ]
