# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0031_auto_20180405_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaBasico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_basico', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Tema Básico')),
            ],
            options={
                'verbose_name': 'Tema Básico',
                'verbose_name_plural': 'Temas Básicos',
            },
        ),
    ]
