# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0032_temabasico'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='tema_basico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artigos.TemaBasico', verbose_name='Tema Basico'),
        ),
    ]
