# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0033_artigo_tema_basico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='categoria',
        ),
        migrations.AddField(
            model_name='artigo',
            name='url',
            field=models.SlugField(help_text='a user friendly url', max_length=60, null=True, verbose_name='user friendly url'),
        ),
    ]
