# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0034_auto_20180502_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='dd_top',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='exames_top',
        ),
    ]
