# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0035_auto_20180503_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='ordem',
            field=models.CharField(max_length=250, null=True, verbose_name='Ordem'),
        ),
    ]
