# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0036_tema_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='artigo_inativo',
            field=models.BooleanField(default=False, help_text='Se marcado, o artigo sera mostrado como inativo', verbose_name='Artigo inativo'),
        ),
    ]
